In [2]:
s = 'abscfdriewfn'

In [3]:
s[2:-4]

'scfdri'

In [4]:
s[-3:-6]

''

In [7]:
add = lambda x,y : x+y
add(20,30)

50

In [8]:
s3 = set()

In [9]:
type(s3)

set

In [10]:
class person:
    pass
    

In [11]:
p1 = person()

In [12]:
type(p1)

__main__.person

In [13]:
class student:
    def __init__(self , name , surname , yob):
        self.name = name
        self.surname = surname
        self.yob = yob

In [19]:
obj = student("Krushna" , "Sonar" , 2004 )

In [21]:
a = range(5,20,5)

In [23]:
obj.name

'Krushna'

access specifies

In [29]:
class test:
    def __init__(self , name , surname , yob):
        self.__name = name
        self._surname = surname
        self.yob = yob

In [30]:
p = test("krushna" , "sonar"  , 2004)

In [31]:
p._surname

'sonar'

In [35]:
p.__dict__

{'_test__name': 'krushna', '_surname': 'sonar', 'yob': 2004}

In [37]:
p._test__name

'krushna'

numpy = numerical python

In [38]:
import numpy as np

In [40]:
arr = np.arange(1,26)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [45]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
arr[0:3,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [50]:
arr2d = arr.reshape(5,5)

In [51]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
arr2d[2,1]

np.int64(12)

In [54]:
arr2d[2:3,1:4]

array([[12, 13, 14]])

In [55]:
arr2d[1:-1,4:]

array([[10],
       [15],
       [20]])

In [56]:
arr2d[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
arr2d[[1,2],[1,3]]

array([ 7, 14])

In [63]:
arr2d[[0,-1] , [0,-1]]

array([ 1, 25])

In [68]:
arr2d[[0,-1],[-2,1]]

array([ 4, 22])




NUMPY




In [69]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
a1 = np.arange(0,11)

In [71]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a1 / a1

C:\Users\BusinessComputers.in\AppData\Local\Temp\ipykernel_12616\1108374187.py:1: RuntimeWarning: invalid value encountered in divide
  a1 / a1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
1/a1

C:\Users\BusinessComputers.in\AppData\Local\Temp\ipykernel_12616\2609805251.py:1: RuntimeWarning: divide by zero encountered in divide
  1/a1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [74]:
a1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [75]:
np.log(a1)

C:\Users\BusinessComputers.in\AppData\Local\Temp\ipykernel_12616\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [76]:
import pandas as pd

In [77]:
d1 = [100,200,300,400,500
     ]

In [79]:
pd.Series(d1)

0    100
1    200
2    300
3    400
4    500
dtype: int64

here list is converted in series

In [83]:
d2 = ['a','b','c','d','e']

In [84]:
pd.Series(d2)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [85]:
pd.Series(d1,d2)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [86]:
pd.Series(d2,d1)


100    a
200    b
300    c
400    d
500    e
dtype: object

we can interchange columns

In [87]:
s1 = pd.Series([10,20,30,40,50],['pune','mumbai','delhi','patna','bihar'])
s2 = pd.Series([10,20,30,40,50],['pune','mumbai','delhi','chennai','bihar'])


In [88]:
s1

pune      10
mumbai    20
delhi     30
patna     40
bihar     50
dtype: int64

In [89]:
s2

pune       10
mumbai     20
delhi      30
chennai    40
bihar      50
dtype: int64

In [90]:
s1+s2

bihar      100.0
chennai      NaN
delhi       60.0
mumbai      40.0
patna        NaN
pune        20.0
dtype: float64