In [4]:
import numpy as np
import pandas as pd

data = pd.read_csv("Advertising.csv")

In [5]:
data

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [8]:
np.random.seed(12345)

nums = np.random.rand(len(data))

In [9]:
nums

array([9.29616093e-01, 3.16375555e-01, 1.83918812e-01, 2.04560279e-01,
       5.67725029e-01, 5.95544703e-01, 9.64514520e-01, 6.53177097e-01,
       7.48906638e-01, 6.53569871e-01, 7.47714809e-01, 9.61306736e-01,
       8.38829794e-03, 1.06444377e-01, 2.98703714e-01, 6.56411183e-01,
       8.09812553e-01, 8.72175914e-01, 9.64647597e-01, 7.23685347e-01,
       6.42475328e-01, 7.17453621e-01, 4.67599007e-01, 3.25584678e-01,
       4.39644606e-01, 7.29689083e-01, 9.94014586e-01, 6.76873712e-01,
       7.90822518e-01, 1.70914258e-01, 2.68492758e-02, 8.00370244e-01,
       9.03722538e-01, 2.46762104e-02, 4.91747318e-01, 5.26255167e-01,
       5.96366010e-01, 5.19575451e-02, 8.95089528e-01, 7.28266180e-01,
       8.18350011e-01, 5.00222753e-01, 8.10189409e-01, 9.59685257e-02,
       2.18950044e-01, 2.58719062e-01, 4.68105754e-01, 4.59373203e-01,
       7.09509780e-01, 1.78053006e-01, 5.31449884e-01, 1.67742229e-01,
       7.68813918e-01, 9.28170549e-01, 6.09493658e-01, 1.50183495e-01,
      

In [10]:
mask_large = nums > 0.5

In [11]:
mask_large

array([ True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True, False, False, False,  True,  True,
        True,  True, False, False,  True,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True, False, False,
       False, False, False,  True, False,  True, False,  True,  True,
        True, False, False, False,  True,  True, False, False,  True,
       False, False,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False,  True, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False, False, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False, False,

In [13]:
data["Scale"] = "SMALL"

In [14]:
data

Unnamed: 0     TV  radio  newspaper  sales  Scale
0             1  230.1   37.8       69.2   22.1  SMALL
1             2   44.5   39.3       45.1   10.4  SMALL
2             3   17.2   45.9       69.3    9.3  SMALL
3             4  151.5   41.3       58.5   18.5  SMALL
4             5  180.8   10.8       58.4   12.9  SMALL
..          ...    ...    ...        ...    ...    ...
195         196   38.2    3.7       13.8    7.6  SMALL
196         197   94.2    4.9        8.1    9.7  SMALL
197         198  177.0    9.3        6.4   12.8  SMALL
198         199  283.6   42.0       66.2   25.5  SMALL
199         200  232.1    8.6        8.7   13.4  SMALL

[200 rows x 6 columns]

In [20]:
data.loc[mask_large , "Scale"]= "LARGE"    #loc = location   . to work on row use ilocation[]

In [21]:
data

Unnamed: 0     TV  radio  newspaper  sales  Scale
0             1  230.1   37.8       69.2   22.1  LARGE
1             2   44.5   39.3       45.1   10.4  SMALL
2             3   17.2   45.9       69.3    9.3  SMALL
3             4  151.5   41.3       58.5   18.5  SMALL
4             5  180.8   10.8       58.4   12.9  LARGE
..          ...    ...    ...        ...    ...    ...
195         196   38.2    3.7       13.8    7.6  SMALL
196         197   94.2    4.9        8.1    9.7  SMALL
197         198  177.0    9.3        6.4   12.8  SMALL
198         199  283.6   42.0       66.2   25.5  SMALL
199         200  232.1    8.6        8.7   13.4  LARGE

[200 rows x 6 columns]

In [22]:
data['Scale'].unique()

array(['LARGE', 'SMALL'], dtype=object)

In [23]:
data.head()

Unnamed: 0     TV  radio  newspaper  sales  Scale
0           1  230.1   37.8       69.2   22.1  LARGE
1           2   44.5   39.3       45.1   10.4  SMALL
2           3   17.2   45.9       69.3    9.3  SMALL
3           4  151.5   41.3       58.5   18.5  SMALL
4           5  180.8   10.8       58.4   12.9  LARGE

In [24]:
data['IsLarge'] = data.Scale.map({'LARGE':1,'SMALL':0})
data.head()

Unnamed: 0     TV  radio  newspaper  sales  Scale  IsLarge
0           1  230.1   37.8       69.2   22.1  LARGE        1
1           2   44.5   39.3       45.1   10.4  SMALL        0
2           3   17.2   45.9       69.3    9.3  SMALL        0
3           4  151.5   41.3       58.5   18.5  SMALL        0
4           5  180.8   10.8       58.4   12.9  LARGE        1

In [42]:
np.random.seed(12)
nums = np.random.rand(len(data))
mask_suburban = (nums >0.33) &(nums < 0.66)
mask_urban = nums > 0.66
data["Target Geography"] = "Rural"
data.loc[mask_suburban ,"Target Geography"] = "suburban"
data.loc[mask_urban , "Target Geography"] = "urban"
data.head()

Unnamed: 0     TV  radio  newspaper  sales  Scale  IsLarge  \
0           1  230.1   37.8       69.2   22.1  LARGE        1   
1           2   44.5   39.3       45.1   10.4  SMALL        0   
2           3   17.2   45.9       69.3    9.3  SMALL        0   
3           4  151.5   41.3       58.5   18.5  SMALL        0   
4           5  180.8   10.8       58.4   12.9  LARGE        1   

  Target Geography Target Geography   
0            Rural               NaN  
1            urban             urban  
2            Rural               NaN  
3         suburban               NaN  
4            Rural               NaN

In [43]:
mask_suburban  #mask_urban will also give true false data

array([False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True, False, False, False,  True, False,
       False, False, False,  True,  True, False,  True, False, False,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False,  True,  True, False, False,  True,  True,  True,
        True, False, False, False,  True, False, False, False, False,
       False,  True,

In [44]:
data

Unnamed: 0     TV  radio  newspaper  sales  Scale  IsLarge  \
0             1  230.1   37.8       69.2   22.1  LARGE        1   
1             2   44.5   39.3       45.1   10.4  SMALL        0   
2             3   17.2   45.9       69.3    9.3  SMALL        0   
3             4  151.5   41.3       58.5   18.5  SMALL        0   
4             5  180.8   10.8       58.4   12.9  LARGE        1   
..          ...    ...    ...        ...    ...    ...      ...   
195         196   38.2    3.7       13.8    7.6  SMALL        0   
196         197   94.2    4.9        8.1    9.7  SMALL        0   
197         198  177.0    9.3        6.4   12.8  SMALL        0   
198         199  283.6   42.0       66.2   25.5  SMALL        0   
199         200  232.1    8.6        8.7   13.4  LARGE        1   

    Target Geography Target Geography   
0              Rural               NaN  
1              urban             urban  
2              Rural               NaN  
3           suburban               NaN  
4              Rural               NaN  
..               ...               ...  
195         suburban               NaN  
196         suburban               NaN  
197            urban             urban  
198            urban             urban  
199            urban             urban  

[200 rows x 9 columns]

In [47]:
pd.get_dummies(data["Target Geography"], prefix = "Target Geography")

Target Geography_Rural  Target Geography_suburban  Target Geography_urban
0                      True                      False                   False
1                     False                      False                    True
2                      True                      False                   False
3                     False                       True                   False
4                      True                      False                   False
..                      ...                        ...                     ...
195                   False                       True                   False
196                   False                       True                   False
197                   False                      False                    True
198                   False                      False                    True
199                   False                      False                    True

[200 rows x 3 columns]

In [50]:
area_dummies = pd.get_dummies(data["Target Geography"], prefix = "Target Geography").iloc[: , 1:]

In [52]:
data = pd.concat([data, area_dummies] , axis = 1)
data.head()

Unnamed: 0     TV  radio  newspaper  sales  Scale  IsLarge  \
0           1  230.1   37.8       69.2   22.1  LARGE        1   
1           2   44.5   39.3       45.1   10.4  SMALL        0   
2           3   17.2   45.9       69.3    9.3  SMALL        0   
3           4  151.5   41.3       58.5   18.5  SMALL        0   
4           5  180.8   10.8       58.4   12.9  LARGE        1   

  Target Geography Target Geography   Target Geography_suburban  \
0            Rural               NaN                      False   
1            urban             urban                      False   
2            Rural               NaN                      False   
3         suburban               NaN                       True   
4            Rural               NaN                      False   

   Target Geography_urban  
0                   False  
1                    True  
2                   False  
3                   False  
4                   False

In [53]:
!python --version


Python 3.13.5


.
.
.


something new 


.
.
.